SimpleGuna/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from sg_sosial import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sg_sosial.urls')),
    path('keluar/', views.keluar, name='keluar'),
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('', views.masuk, name='masuk'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sg_sosial/urls.py
from functools import partial
from os import name
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.masuk, name='login'),
    path('', views.index, name='index'),
    path('daftar/', views.daftar, name='signup'),
]

sg_sosial/models.py
from SimpleGuna.settings import MEDIA_DIR
from django.db import models
from django.db.models.fields import NullBooleanField
from django.http import request
from django.core.validators import MaxValueValidator
from django.contrib.auth.models import User
from django.utils import timezone
import os
from django import forms

class UserAkun(models.Model):
    nm_depan = models.TextField(max_length=150)
    nm_belakang = models.TextField(max_length=150)
    username = models.TextField(max_length=150)
    email = models.EmailField(max_length=150)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.username
    def get_username(self):
        return self.username
    
    def get_password(self):
        return self.password

    def get_nm_depan(self):
        return self.nm_depan
    
    def get_nm_belakang(self):
        return self.nm_belakang
    
    def get_session(self):
        self.ambilsesi = request.session[self.username]
        return self.ambilsesi


def fldr_usr_pp(instance, filename):
    flder_usr ='{}/{}'.format(MEDIA_DIR, instance.user)
    if not os.path.exists(flder_usr):
        os.mkdir(flder_usr)
    elif not os.path.exists(flder_usr+'/poto_profile/'):
        os.mkdir(flder_usr+'/poto_profile/')
    fldernya = '{0}/poto_profile/{1}'.format(instance.user, filename)
    return fldernya

class IniUsrProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nama_depan = models.CharField(max_length=200, blank=True, null=True)
    nama_belakang = models.CharField(max_length=200, blank=True, null=True)
    foto_profile = models.ImageField(upload_to=fldr_usr_pp, blank=True, null = True)

    def __str__(self):
        return self.user.username

def fldr_usr_foto(instance, filename):
    flder_usr = '{}/{}'.format(MEDIA_DIR, instance.user)
    if not os.path.exists(flder_usr):
        os.mkdir(flder_usr)
    elif not os.path.exists(flder_usr+'/sts_foto/'):
        os.mkdir(flder_usr+'/sts_foto/')
    fldernya = '{0}/sts_foto/{1}'.format(instance.user, filename)
    return fldernya

def fldr_usr_video(instance, filename):
    flder_usr = '{}/{}'.format(MEDIA_DIR, instance.user)
    if not os.path.exists(flder_usr):
        os.mkdir(flder_usr)
    elif not os.path.exists(flder_usr+'/sts_video/'):
        os.mkdir(flder_usr+'/sts_video/')
    fldernya = '{0}/sts_video/{1}'.format(instance.user, filename)
    return fldernya

class StatusGuna(models.Model):
    user = models.ForeignKey(User, related_name="StatusGuna", on_delete=models.CASCADE)
    st = models.ForeignKey(IniUsrProfile, related_name="StatusGuna", on_delete=models.CASCADE)
    foto_profile = models.ImageField(upload_to=fldr_usr_pp, blank=True, null = True)
    status = models.CharField(max_length=300, blank=True, null=True)
    status_foto = models.ImageField(upload_to=fldr_usr_foto, blank=True, null=True)
    status_video = models.FileField(upload_to=fldr_usr_video, blank=True, null=True)
    status_tanggal = models.DateField(default=timezone.now)
    status_suka = models.PositiveIntegerField(null=True)
    status_komen = models.ManyToManyField(IniUsrProfile, related_name="status_komen", blank=True)
    status_bagi = models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.user.username

    def hitungsuka(self):
        return self.status_suka.count()

class KomenGuna(models.Model):
    stData = models.ForeignKey(StatusGuna, on_delete=models.CASCADE, related_name="KomenGuna")
    st_profile = models.ForeignKey(IniUsrProfile, related_name='KomenGuna', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='KomenGuna', on_delete=models.CASCADE)
    isiKomen = models.CharField(max_length=300, null=True, blank=True)
    tanggal_komen = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.user.username

sg_sosial/forms.py
from datetime import datetime
from django import forms
from django.db.models import fields
from .models import IniUsrProfile, KomenGuna, StatusGuna
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')

class IniProfileForm(forms.ModelForm):
    class Meta():
        model = IniUsrProfile
        fields = ('nama_depan', 'nama_belakang', 'foto_profile')

class StsUsr(forms.ModelForm):
    class Meta():
        model = User
        fields = ('username',)

class StsForm(forms.ModelForm):
    class Meta():
        model = StatusGuna
        fields = (
            'status',
            'status_foto',
            'status_video',
        )

class KomenForm(forms.ModelForm):
    isiKomen = forms.CharField(required=True)
    class Meta():
        model = KomenGuna
        fields = (
            'isiKomen',
            'stData',
        )

sg_sosial/views.py
from os import stat
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse, request
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from .models import IniUsrProfile, KomenGuna, StatusGuna
from .forms import  KomenForm, StsForm, StsUsr, UserForm, IniProfileForm
# Create your views here.
def index(request):
    if request.user.is_authenticated:
        ambil_dt = IniUsrProfile.objects.filter(user=request.user.id).first()
        data = {
            'bio' : ambil_dt
        }
        return render(request, 'home.html', data)
    return render(request, 'home.html')


@login_required
def su(request):
    return render(request, 'home.html')

@login_required
def keluar(request):
    logout(request)
    return render(request, 'login.html')


def daftar(request):
    if request.user.is_authenticated:
        return redirect('/')
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = IniProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            print(profile.user)
            if 'foto_profile' in request.FILES:
                print(request.FILES['foto_profile'])
                profile.foto_profile = request.FILES['foto_profile']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = IniProfileForm()
    return render(request, 'daftar.html', {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

def masuk(request):
    if request.user.is_authenticated:
        return redirect('/home/')
    if request.method == 'POST':
        cek_user= request.POST.get('username')
        cek_pass = request.POST.get('password')
        user = authenticate(username=cek_user, password=cek_pass)
        if user:
            if user.is_active:
                login(request,user)
                return redirect('/home/')
            else:
                print("akun anda tidak aktif")
        else:
            print("ada yang mencoba login")
            print("dengan username : {} dan password : {}".format(cek_user, cek_pass))
            return render(request, 'login.html')
    else:
        return render(request, 'login.html')


def home(request):
    if request.user.is_authenticated:
        ambil_dt = IniUsrProfile.objects.filter(user=request.user.id).first()
        ambil_stts = StatusGuna.objects.all().select_related('user', 'st')
        ambil_komen = KomenGuna.objects.all().select_related('user', 'stData')
        hitung_komen = KomenGuna.objects.all().select_related('stData').count()
        data = {
            'bio' : ambil_dt,
            'st_dt' : ambil_stts,
            'komen' : ambil_komen,
            'hitung' : hitung_komen,
        }
        print(ambil_dt.foto_profile)
        print(ambil_stts)
        print("ini komen")
        print(ambil_komen)
       
        print(data)
        if request.method == "POST":
            user_status =  ambil_dt.user
            user_st = ambil_dt
            dt_usr_status = StsForm(data=request.POST)
            dt_km = KomenForm(data=request.POST)
            if 'sv_status' in request.POST:
                user = user_status
                st = user_st
                data_status = dt_usr_status.save(commit=False)
                data_status.user = user
                data_status.st = st
                if 'status_foto' in request.FILES:
                    print(request.FILES['status_foto'])
                    data_status.status_foto = request.FILES['status_foto']
                    print(data_status.status_foto)
                elif 'status_video' in request.FILES:
                    print(request.FILES['status_vieeo'])
                    data_status.status_video = request.FILES['status_video']
                    print(data_status.status_video)
                data_status.save()
            else:
                print(dt_usr_status.errors)
            
            if 'isiKomen' in request.POST:
                print("ini request komen")
                print(request.POST['isiKomen'])
                user = user_st
                user_p = ambil_dt.user
                data_komen = dt_km.save(commit=False)
                data_komen.st_profile = user
                data_komen.user = user_p
                print(data_komen)
                data_komen.save()
            else:
                print(dt_km.errors)

        else:
            user_status = StsUsr()
            dt_usr_status = StsForm()
            dt_km = KomenForm()
        return render(request, 'home.html', data)
    else:
        return redirect('/')

sg_sosial/templates/daftar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
{% include "styles/head.html"%}

<body>

    <!-- Pageloader -->
    <div class="pageloader"></div>
    <div class="infraloader is-active"></div>
    <div class="signup-wrapper">

        <!--Fake navigation-->
        <div class="fake-nav">
            <a href="index.html" class="logo">
                <img class="light-image" src="{% static 'img/logo/simple-guna-bold.png' %}" width="112" height="28" alt="" style="margin-top: 30px;">
                <img class="dark-image" src="{% static 'img/logo/simple-guna-bold.png' %}" width="112" height="28" alt="" style="margin-top: 30px;">
            </a>
        </div>

        <div class="container">
            <!--Container-->
            <div class="login-container is-centered">
                <div class="columns is-vcentered">
                    <div class="column">

                        <h2 class="form-title has-text-centered">Hallo Bro</h2>
                        <h3 class="form-subtitle has-text-centered">Belum daftar ya? yuk daftar sekarang.</h3>

                        <!--Form-->
                        <div class="login-form">
                            <form enctype="multipart/form-data" method="POST">
                                {% csrf_token %}
                                <div class="form-panel">
                                    <div class="columns is-multiline">
                                        <div class="column is-6">
                                            <div class="field">
                                                <label>Nama Depan</label>
                                                <div class="control">
                                                    <input type="text" class="input" name="nama_depan" placeholder="Masukkan nama depan">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="column is-6">
                                            <div class="field">
                                                <label>Nama Belakang</label>
                                                <div class="control">
                                                    <input type="text" class="input" name="nama_belakang" placeholder="Masukkan nama belakang">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="column is-12">
                                            <div class="field">
                                                <label>Username</label>
                                                <div class="control">
                                                    <input type="text" class="input" name="username" placeholder="Masukkan email address">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="column is-12">
                                            <div class="field">
                                                <label>Email</label>
                                                <div class="control">
                                                    <input type="text" class="input" name="email" placeholder="Masukkan email address">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="column is-12">
                                            <div class="field">
                                                <label>Password</label>
                                                <div class="control">
                                                    <input type="password" class="input" name="password" placeholder="Masukkan passowrd">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="column is 12">
                                            <div class="field">
                                                <label>Foto Profile</label>
                                                <input type="file" name="foto_profile" accept="image/*" id="id_foto_profile">
                                            </div>
                                        </div>
                                        <div class="column is-12">
                                        <!-- ini space -->
                                        </div>
                                    </div>
                                </div>

                                <div class="buttons mt-2">
                                    <input type="submit" class="button is-solid primary-button is-fullwidth raised" value="Submit">
                                    
                                </div>
                            </form>


                            <div class="account-link has-text-centered">
                                <a href="/" target="_blank">Udah punya akun? masuk yuk</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include "styles/foot.html"%}

    <script src="{% static 'js/signup.js' %}"></script>
    
</body>
</html>

sg_sosial/templates/index.html
<html>
    <head>
        <title>Tes halaman utama</title>
    </head>
    <body>
        <h1>Tesss</h1>
    </body>
    
</html>

sg_sosial/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% include "styles/head.html"%}

<body class="is-white">

    <!-- Pageloader -->
    <div class="pageloader"></div>
    <div class="infraloader is-active"></div>
    <div class="login-wrapper">

        <!-- Main Wrapper -->
        <div class="login-wrapper columns is-gapless">
            <!--Left Side (Desktop Only)-->
            <div class="column is-6 is-hidden-mobile hero-banner">
                <div class="hero is-fullheight is-login">
                    <div class="hero-body">
                        <div class="container">
                            <div class="left-caption">
                                <h2>Hayuk Masuk SimpleGuna ^_^.</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--Right Side-->
            <div class="column is-6">
                <div class="hero form-hero is-fullheight">
                    <!--Logo-->
                    <div class="logo-wrap">
                        <div class="wrap-inner">
                            <img src="{% static 'img/logo/simple-guna-wblack.png' %}" alt="">
                        </div>
                    </div>
                    <!--Login Form-->
                    <div class="hero-body">
                        <div class="form-wrapper">
                            <!--Avatar-->
                            <div class="avatar">
                                <div class="badge">
                                    <i data-feather="check"></i>
                                </div>
                                <img src="https://placehold.it/128x128" data-demo-src="{% static 'img/logo/simple-guna-wblack.png' %}" alt="">
                            </div>
                            <!--Form-->
                            <div class="login-form">
                                <form action="{% url 'login' %}" method="POST">
                                    {% csrf_token %}
                                <div class="field">
                                    <div class="control">
                                        <input class="input email-input" type="text" name="username" placeholder="username">
                                        <div class="input-icon">
                                            <i data-feather="user"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="field">
                                    <div class="control">
                                        <input class="input password-input" type="password" name="password" placeholder="●●●●●●●">
                                        <div class="input-icon">
                                            <i data-feather="lock"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="field">
                                    <div class="control">
                                        <input type="submit" class="button is-solid primary-button raised is-rounded is-fullwidth" value="Login">
                                    </div>
                                </div>
                                </form>
                            </div>
                            <div class="section forgot-password">
                                <div class="has-text-centered">
                                    <a href="/daftar" target="_blank">Belum punya akun? yuk daftar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include "styles/foot.html"%}

    <!-- Landing page js -->

    <!-- Signup page js -->

    <!-- Feed pages js -->

    <!-- profile js -->

    <!-- stories js -->

    <!-- friends js -->

    <!-- questions js -->

    <!-- video js -->

    <!-- events js -->

    <!-- news js -->

    <!-- shop js -->

    <!-- inbox js -->

    <!-- settings js -->

    <!-- map page js -->

    <!-- elements page js -->
</body>


<!-- Mirrored from friendkit.cssninja.io/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 23 Jun 2021 13:51:15 GMT -->
</html>